### PR TITLE
Fix backend tests

### LINKED ISSUE #348: Fix backend tests
With the update in #332 where keys are now user IDs, a lot of the backend tests are breaking. We need to update the tests and fixture data so that they pass with this new framework.

### PR DESCRIPTION
**Pull request by caiyingshen**
Resolves #348 

<Add Screenshots!>

### CODE REVIEW

File: backend/tests/mongo_utils.js [hunk 1]
```diff
@@ -6,30 +6,22 @@ let mongoServer
...
+  mongoServer
+    .getConnectionString()
+    .then(mongoUri => {
+      return mongoose.connect(mongoUri, {}, err => {
+        if (err) {
+          done(err)
+        }
+      })
+    })
+    .then(() => done())
```
Comment (angadgarg25) [inline backend/tests/mongo_utils.js]: is uncommenting this what fixed it? This was the old version that I tried to rewrite with async/await with lines 19-22. Tbh idk how this even runs since `done` isn't defined anymore.

Comment (caiyingshen) [reply backend/tests/mongo_utils.js]: Noo it fixed one of them where mongo wasn't returning the _id value of an object. When i changed the leads key to `director` instead of `lead` tho a bunch of the tests passed

File: backend/src/middleware/auth.js [hunk 2]
```diff
@@ -9,6 +9,7 @@ const auth = async (req, res, next) => {
   if (key != undefined) {
     // removed && key.length === 11
     // Can add this rule if wanted
+    console.log('reached here')
 
     // check to see if URL is for register, since the key would not be recorded yet
     if (req.method === 'POST' && req.url.includes('/user/')) {
```
Comment (angadgarg25) [inline backend/src/middleware/auth.js]: the last failure on circle CI is probably because this line. Since `req` only has the `query` key, `req.url === undefined` so it'll throw an error like `cannot call method includes on undefined`

File: backend/tests/mongo_utils.js (hunk 1 above)
Comment (angadgarg25) [reply backend/tests/mongo_utils.js]: ok lets attempt to get rid of it again? if that doesn't work we can leave it, but I don't really understand how leaving this isn't causing everything to break lol
